Algoritmo "Menor_de_tres"

Var
Numero1, Numero2, Numero3, Menor : inteiro
Inicio
Escreva("Digite o valor do Primeiro Numero:")
Leia(Numero1)
Escreva("Digite o valor do Segundo Numero:")
Leia(Numero2)
Escreva("Digitem o valor do Terceiro Numero")
Leia(Numero3)
se (Numero1 <= Numero2) e (Numero1 <= Numero3) entao
Menor <- Numero1
senao
se (Numero2 <= 3) entao
Menor <- numero2
senao
Menor <- Numero3
fimse
fimse
Escreval("O menor número é: ", Menor)


Fimalgoritmo
