Algoritmo "Idade/Nome"

Var
nome1, nome2: caractere
idade1, idade2: inteiro

Inicio
Escreva("Digite seu nome: ")
leia(nome1)
Escreva("Digite seu nome: ")
leia(nome2)
Escreva("Digite sua idade")
leia(idade1)
Escreva("Digite sua idade")
leia(idade2)

Escreval("Dados da primeira pessoa:")
Escreval("Nome: ", nome1)
Escreval("Idade: ", idade1)
Escreval("Dados da segunda pessoa: ")
Escreval("Nome: ", nome2)
Escreval("Idade: ", idade2)


Fimalgoritmo
